#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 5.3
#  in conjunction with Tcl version 8.6
#    May 21, 2020 02:59:40 PM PDT  platform: Linux

'''The employee login screen.'''

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk
#import tkinter.messagebox
import student_entry_screen


class LoginScreen(tk.Frame):
    '''This class populates the window with login screen stuff.'''
    def __init__(self, master):
        tk.Frame.__init__(self, master)

        self.configure(bg="white")

        font10 = "-family {Noto Sans} -size 18"
        font9 = "-family {Noto Sans} -size 24"

        master.title("Dolphin Dollars Employee Login")

        label_1 = tk.Label(self)
        label_1.place(relx=0.5, rely=0.067, anchor="center")
        label_1.configure(background="#ffffff", cursor="fleur", font=font9,
                          foreground="#ed1c24", text='''Dolphin Dollars''')

        label_2 = tk.Label(self)
        label_2.place(relx=0.5, rely=0.178, anchor="center")
        label_2.configure(background="#ffffff", cursor="fleur",
                          font=font10, text='''Employee Login''')

        label_3 = tk.Label(self)
        label_3.place(relx=0.083, rely=0.489, height=23, width=90)
        label_3.configure(background="#ffffff", justify='right', text='''Employee ID:''')

        label_4 = tk.Label(self)
        label_4.place(relx=0.1, rely=0.578, height=23, width=78)
        label_4.configure(background="#ffffff", justify='right',
                          text='''Password:''')

        self.employee_id_entry = tk.Entry(self)
        self.employee_id_entry.place(relx=0.25, rely=0.489, height=23, relwidth=0.527)
        self.employee_id_entry.configure(background="white", font="TkFixedFont")

        self.password_entry = tk.Entry(self, show="*")
        self.password_entry.place(relx=0.25, rely=0.578, height=23, relwidth=0.527)
        self.password_entry.configure(background="white", font="TkFixedFont")

        login_button = tk.Button(self)
        login_button.place(relx=0.45, rely=0.667, height=33, width=61)
        login_button.configure(background="#ed1c24", foreground="#ffffff",
                               text='''Log In''', command=self.authenticate)

    def authenticate(self):
        '''Contacts the database to authenticate the employee.'''
        emp_id = self.employee_id_entry.get()

        if not emp_id or not self.password_entry.get():
            tk.messagebox.showerror("Enter an ID+Password",
                                    "Please enter your credentials to log in.")
            return

        cursor = self.master.execute(
            "SELECT AuthenticateEmployee({}, '{}');".format(emp_id, self.password_entry.get()))

        for i in cursor:
            for j in i:
                if j == 1:
                    self.master.switch_frame(student_entry_screen.StudentEntryScreen, emp_id)
                else:
                    tk.messagebox.showerror("Incorrect ID/Password",
                                            "Please check your credentials and try again.")
                    return
